# Boolean Tensors

The language `fin_rel` contains:

- **Types:** Finite enumerated sets (in the form $\lbrace 0,...,n-1 \rbrace$ for size $n \geq 1$).
- **Boxes:** Finitary relations between finite enumerated sets, parametrised by Boolean tensors.

Specifically, a relation $R \subseteq \prod\limits_{k=0}^{m-1} {0,...,n_k}$ can be densely represented by its indicator function:

$$
1_R: \prod_{k=0}^{m-1} {0,...,n_k} \rightarrow \lbrace 0, 1 \rbrace
$$

Embedding $\lbrace 0, 1 \rbrace$ with the structure of the Boolean semiring, such indicator functions take the form of Boolean tensors.

In [12]:
import numpy as np
from tensorsat.lang.fin_rel import FinSet, FinRel

Boxes in `fin_rel` are parametrised by Boolean tensors: these can be accessed via the `tensor` property of `FinRel` instances, in the form of NumPy UInt8 arrays.
As an example, consider the `and_` operator from the `bincirc` library.

In [4]:
from tensorsat.lib.bincirc import and_
and_.tensor

array([[[1, 0],
        [1, 0]],

       [[1, 0],
        [0, 1]]], dtype=uint8)

The `and_` gate is a ternary relation:

$$
\texttt{and\_} :=
\left\lbrace (a, b, a\&b) \middle| a, b \in \lbrace 0, 1 \rbrace \right\rbrace
\subset \lbrace 0, 1 \rbrace^3
$$

By our convention, input components are listed before output components.

For a relation $R \subseteq \prod\limits_{k=0}^{m-1} {0,...,n_k}$, the Boolean tensor has rank $m$ and shape $(n_0,...,n_{m-1})$.
For the `and_` gate, the rank is 3 and the shape is `(2, 2, 2)`.

In [9]:
print(f"{len(and_.tensor.shape) = }") # rank
print(f"{and_.tensor.shape = }") # shape
# (2, 2, 2)
#        ^ 1 output bit
#  ^^^^ 2 input bits

len(and_.tensor.shape) = 3
and_.tensor.shape = (2, 2, 2)


We can enumerate the set of tuples in a relation by iterating over all elements of the relation's domain, using them to index the Boolean tensor, and keeping those where the tensor has value 1.

In [22]:
print({
    point
    for point in np.ndindex(and_.tensor.shape)
    if and_.tensor[point]
})
# { (0 , 0 , 0), (0 , 1 , 0), (1 , 0 , 0), (1 , 1 , 1) }
#    0 & 0 = 0    0 & 1 = 0    1 & 0 = 0    1 & 1 = 1

{(1, 0, 0), (0, 0, 0), (1, 1, 1), (0, 1, 0)}


By flattening the input and output components, we can also obtain a more traditional representation of the gate as a Boolean matrix. According to our convention, where input components appear first, the resultin matrix acts naturally to the left on row Boolean vectors.
In this representation, the rows are the indicator functions for the output values of the gate on its 4 inputs.

In [23]:
and_.tensor.reshape(4, 2)
# [[1, 0], < indicator of 0 ∈ {0, 1}, the output on (0, 0)
#  [1, 0], < indicator of 0 ∈ {0, 1}, the output on (0, 1)
#  [1, 0], < indicator of 0 ∈ {0, 1}, the output on (1, 0)
#  [0, 1]] < indicator of 1 ∈ {0, 1}, the output on (1, 1)

array([[1, 0],
       [1, 0],
       [1, 0],
       [0, 1]], dtype=uint8)

To obtain the more traditional presentation, acting to the right on column Boolean vectors, it suffices to take the transpose.
In this representations, the columns are the indicator functions for the output values instead.

In [24]:
and_.tensor.reshape(4, 2).T
# [[1, 1, 1, 0],
#  [0, 0, 0, 1]]
#            ^ indicator of 1 ∈ {0, 1}
#         ^ indicator of 0 ∈ {0, 1}
#      ^ indicator of 0 ∈ {0, 1}
#   ^ indicator of 0 ∈ {0, 1}

array([[1, 1, 1, 0],
       [0, 0, 0, 1]], dtype=uint8)

**TODO:** Showcase Boolean tensor network contraction for satisfiability.